### ISSUE TITLE
Hmm

### ISSUE THREAD

**Issue by dikiaap** [christoga/razor#2]
Halo bro,

You so young, still junior high school?

**Comment by christoga** [comment]
Iya om, 😁

**Comment by christoga** [comment]
How do you know this "razor" project?
My repo never go popular..
How??🤔

**Comment by dikiaap** [comment]
Haha, ok.
Just found your profile on some repo and I create random issues on your repo.
Yeah, Not popular? i think so :smile:

**Comment by christoga** [comment]
Haha, thanks for visiting some of my project om!😀😁

**Comment by dikiaap** [comment]
Mmmm. mau bikin organisasi? Yang kemarin itu pengen di jadiin organisasi jokes, jadi cuma kontribusi dan buat repo repo yg lucu aja. Haha
Jika pengen buat dan bukan ponorogo doang / bisa orang di worldwide masuk ya gpp.

**Comment by christoga** [comment]
No sir, I want to help you create the website for ponorogojs

**Comment by dikiaap** [comment]
Ya, temen saya juga lagi ngerjain project, pasti dia gak mungkin ngelola repo nya dan saya juga gak mau organisasinya terbengkalai begitu saja setelah web nya selesai. Haha.

Jadi lain kali akan lebih baik.
Thanks for feed back man & keep open source. :+1:

**Comment by christoga** [comment]
#opensourceisthebest

**Comment by christoga** [comment]
Because I actually live in Jakarta, not Ponorogo :grin:

**Comment by dikiaap** [comment]
Oh, nice. haha.
https://jakartajs-join.herokuapp.com/ how about jakartajs on slack? they always active?

**Comment by christoga** [comment]
Yeah, they're so loud, That's why I didn't open slack anymore.
I rather use gitter. :smile:

**Comment by dikiaap** [comment]
Haha, okey.
https://github.com/GitIndonesia/awesome-indonesia-repo I will create list organization on gitindonesia repo. Many indonesia community, I don't know on github.
